# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted on first-time issues
newIssueWelcomeComment: >
  ğŸ‰ Welcome to the pucham project! ğŸš€ Thank you for opening your first issue! Make sure to follow our issue template for a smooth collaboration.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted on pull requests from first-time contributors
newPRWelcomeComment: >
  ğŸŒŸ Awesome! You're making a difference! Thanks for your pull request to pucham. ğŸ™Œ Please take a moment to review our contributing guidelines.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted on pull requests merged by a first-time user
firstPRMergeComment: >
  ğŸŠ Hooray! ğŸš€ You just merged your first pull request with pucham! The behaviorbot team is celebrating your achievement. Great job!
