newIssueWelcomeComment: >
  ğŸ‰ Welcome to the pucham project! ğŸš€ Thank you for opening your first issue! Make sure to follow our issue template for a smooth collaboration.

newPRWelcomeComment: >
  ğŸŒŸ Awesome! You're making a difference! Thanks for your pull request to pucham. ğŸ™Œ Please take a moment to review our contributing guidelines.

firstPRMergeComment: >
  ğŸŠ Hooray! ğŸš€ You just merged your first pull request with pucham! The behaviorbot team is celebrating your achievement. Great job!
